### ISSUE TITLE
27. Add project services to Docker Compose

### ISSUE THREAD

**Issue by sergey-morenets** [jakubgrajber/Banking-System-Demo#27]

**Comment by jakubgrajber** [comment]
@sergey-morenets is my current approach okay?

**Comment by sergey-morenets** [comment]
Yes, but now you have to build the sources manually using Maven and then run Docker Compose. Please, think about full automation of this process.

**Comment by jakubgrajber** [comment]
@sergey-morenets is it sth wrong with my config or `RUN mvn install spring-boot:repackage` from your last example runs every time when image is built? It's slower than building whole project manually with Maven and then building images

**Comment by sergey-morenets** [comment]
Because it downloads all the dependencies every time you change pom.xml. If you haven't changed it then Docker uses cached layer with downloaded dependencies.

**Comment by jakubgrajber** [comment]
@sergey-morenets Okay, I am trying to get this docker files done and finally found good solution, but only one of my services (actually with eureka server) doesn't work...

Do you know what causes this error:

`21:29:48.628 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: org.springframework.boot.context.properties.bind.Binder has not been registered
        at org.springframework.boot.DefaultBootstrapContext.lambda$get$1(DefaultBootstrapContext.java:88)
        at org.springframework.boot.DefaultBootstrapContext.getOrElseThrow(DefaultBootstrapContext.java:109)
        at org.springframework.boot.DefaultBootstrapContext.get(DefaultBootstrapContext.java:88)
        at org.springframework.cloud.bootstrap.TextEncryptorConfigBootstrapper.lambda$initialize$0(TextEncryptorConfigBootstrapper.java:49)
        at org.springframework.boot.DefaultBootstrapContext.getInstance(DefaultBootstrapContext.java:119)
        at org.springframework.boot.DefaultBootstrapContext.getOrElseThrow(DefaultBootstrapContext.java:111)
        at org.springframework.boot.DefaultBootstrapContext.get(DefaultBootstrapContext.java:88)
        at org.springframework.cloud.bootstrap.TextEncryptorConfigBootstrapper.lambda$initialize$2(TextEncryptorConfigBootstrapper.java:63)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
        at org.springframework.boot.DefaultBootstrapContext.close(DefaultBootstrapContext.java:133)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:375)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at com.smart.tech.start.EurekaServerApplication.main(EurekaServerApplication.java:11)`

Here is my pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">





    <modelVersion>4.0.0</modelVersion>

    <artifactId>eureka-server</artifactId>
    <version>1.0-SNAPSHOT</version>
    <groupId>com.smart.tech.start</groupId>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>18</maven.compiler.source>
        <maven.compiler.target>18</maven.compiler.target>
        <spring.boot.dependencies.version>2.7.1</spring.boot.dependencies.version>
        <spring.cloud.version>2021.0.0</spring.cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.dependencies.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.smart.tech.start.EurekaServerApplication</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>assemble-all</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`

And dockerfile:

`FROM maven:3-openjdk-18-slim as build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
ADD . $HOME
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME/pom.xml clean package`

`FROM openjdk
COPY --from=build /usr/app/target/eureka-server-1.0-SNAPSHOT-jar-with-dependencies.jar /app/eureka-server.jar
ENTRYPOINT java -jar /app/eureka-server.jar`

**Comment by sergey-morenets** [comment]
@jakubgrajber  The configuration looks fine. Please, investigate the cause of this issue.
But I don't understand why you're working on these infrastructure tasks. I wrote 4 days ago that domain model and REST services are not finished. Please, focus on them. That's core components of this training project. I don't see any progress about these tasks for these 4 days.

**Comment by jakubgrajber** [comment]
@sergey-morenetsI  was struggling with this for so long and wanted to finish this done. I am working on domain model right now.
